version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - ${APP_PORT}:8080
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
      - redis
      - dynamodb-local
    links:
      - dynamodb-local
  database:
    container_name: database
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
    ports:
      - ${PHPMYADMIN_PORT}:80
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "secret"
    volumes:
      - ./data/redis:/data
    ports:
      - ${REDIS_PORT}:6379
  websockets:
    container_name: websockets
    image: olafnorge/laravel:8.1.13-websocket
    environment:
      - LARAVEL_WEBSOCKETS_PORT=${PUSHER_PORT}
    ports:
      - ${PUSHER_PORT}:6001
    volumes:
      - ./:/var/www/html
    depends_on:
      - api
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    ports:
      - ${DYNAMODB_PORT}:8000
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
volumes:
  db-data: ~