name: Deploy RGB API
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy app to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.RGB_AWS_SSH_PEM }}
          HOSTNAME: ${{ secrets.RGB_AWS_HOSTNAME }}
          USERNAME: ${{ secrets.RGB_AWS_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            cd ${{ secrets.RGB_AWS_PATH_PROJECT }}
          '
      - name: Set permissions for directories
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            sudo chown -R $USER:www-data ${{ secrets.RGB_AWS_PATH_PROJECT }}
          '
      - name: Configure Git safe.directory
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            git config --global --add safe.directory ${{ secrets.RGB_AWS_PATH_PROJECT }}
          '
      - name: Fetch latest changes from Git
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master
          '
      - name: Update Composer dependencies
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            composer update --no-dev --prefer-dist --optimize-autoloader
          '
      - name: Set storage directory permissions
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            chmod -R 775 storage
          '
      - name: Clear Laravel configuration cache
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            php artisan config:clear
          '
      - name: Clear Laravel application cache
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            php artisan cache:clear
          '
      - name: Clear Laravel route cache
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            php artisan route:clear
          '
      - name: Bring Laravel application online
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            php artisan up
          '
