name: Deploy Olshop API
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PEM }}
          REMOTE_HOST: ${{ secrets.AWS_HOSTNAME }}
          REMOTE_USER: ${{ secrets.AWS_USERNAME }}
          TARGET: ${{ secrets.AWS_PATH_PROJECT }}
        run: |
          echo "Deployment started ..."
          cd ${{ secrets.AWS_PATH_PROJECT }}
          git checkout .
          git clean -f -d
          git fetch --all
          git reset --hard origin/master
          git pull origin master
          sudo chmod -R 777 bootstrap/cache
          sudo chmod -R 777 storage
          composer update --no-dev --no-interaction --prefer-dist --optimize-autoloader
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          php artisan migrate
          git add .
          git commit -am "Update from automation deploy"
          git push origin master
          echo "Deployment finished!"
