name: Deploy Olshop API
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AWS_SSH_PEM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOSTNAME }} >> ~/.ssh/known_hosts

      # - name: Install PHP and dependencies
      #   run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader

      - name: Deploy to EC2
        run: |
          rsync -avz --delete --exclude-from=".rsyncignore" -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOSTNAME }}:/var/www/html
          ssh -i ~/.ssh/id_rsa ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOSTNAME }} 'cd /var/www/html && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate --force && php artisan config:cache && php artisan route:cache'

      - name: Clear SSH key
        run: rm ~/.ssh/id_rsa

      # - name: Deploy to EC2
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PEM }}
      #     REMOTE_HOST: ${{ secrets.AWS_HOSTNAME }}
      #     REMOTE_USER: ${{ secrets.AWS_USERNAME }}
      #     TARGET: ${{ secrets.AWS_PATH_PROJECT }}
      #   with: 
      #     run: |
      #       git clean -f -d &&
      #       git fetch --all &&
      #       git reset --hard origin/master &&
      #       git pull origin master &&
      #       sudo chmod -R 777 bootstrap/cache &&
      #       sudo chmod -R 777 storage && &&
      #       composer update --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
      #       php artisan config:clear &&
      #       php artisan cache:clear &&
      #       php artisan view:clear &&
      #       php artisan route:clear &&
      #       php artisan migrate &&
      #       git add . &&
      #       git commit -am "Update from automation deploy" &&
      #       git push origin master
