name: Deploy Olshop API
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.AWS_SSH_PEM }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -H ${{ secrets.AWS_HOSTNAME }} >> ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts
      # - name: Deploy to Server
      #   env:
      #     AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
      #     AWS_HOSTNAME: ${{ secrets.AWS_HOSTNAME }}
      #     AWS_PORT: ${{ secrets.AWS_PORT }}
      #     AWS_PATH_PROJECT: /var/www/html/test
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PEM }}
          REMOTE_HOST: ${{ secrets.AWS_HOSTNAME }}
          REMOTE_USER: ${{ secrets.AWS_USERNAME }}
          TARGET: ${{ secrets.AWS_PATH_PROJECT }}
        with: 
          script: |
            git clean -f -d
            git fetch --all
            git reset --hard origin/master
            git pull origin master
            sudo chmod -R 777 bootstrap/cache
            sudo chmod -R 777 storage
            composer update --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan migrate --force
            git add .
            git commit -am "Update from automation deploy"
            git push origin master
