name: Deploy Olshop API
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PEM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOSTNAME }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
          AWS_HOSTNAME: ${{ secrets.AWS_HOSTNAME }}
          AWS_PORT: 22
          AWS_PATH_PROJECT: ${{ secrets.AWS_PATH_PROJECT }}
        run: |
          echo "Deployment started ..."
          cd ${{ env.AWS_PATH_PROJECT }}
          git checkout master
          git fetch --all
          git reset --hard origin/master
          git pull origin master
          composer update --no-dev --prefer-dist --optimize-autoloader
          chmod -R 775 storage
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          php artisan up
          
        
