name: Deploy RGB API
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy app to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.RGB_AWS_SSH_PEM }}
          HOSTNAME: ${{ secrets.RGB_AWS_HOSTNAME }}
          USERNAME: ${{ secrets.RGB_AWS_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            cd ${{ secrets.RGB_AWS_PATH_PROJECT }} &&
            sudo chown -R $USER:www-data ${{ secrets.RGB_AWS_PATH_PROJECT }} &&
            git config --global --add safe.directory ${{ secrets.RGB_AWS_PATH_PROJECT }} &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            composer update --no-dev --prefer-dist --optimize-autoloader &&
            chmod -R 775 storage &&
            php artisan migrate &&
            php artisan config:clear &&
            php artisan cache:clear &&
            php artisan route:clear &&
            php artisan up
          '
