name: Deploy RGB API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy app to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.RGB_AWS_SSH_PEM }}
          HOSTNAME: ${{ secrets.RGB_AWS_HOSTNAME }}
          USERNAME: ${{ secrets.RGB_AWS_USERNAME }}
          PROJECT_PATH: ${{ secrets.RGB_AWS_PATH_PROJECT }}
        run: |
          echo -e "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} 'bash -s' << 'ENDSSH'
            cd "$PROJECT_PATH"
            sudo chown -R $USER:www-data "$PROJECT_PATH"
            git config --global --add safe.directory "$PROJECT_PATH"
            git checkout master
            git fetch --all
            git reset --hard origin/master
            git pull origin master
            composer update --no-dev --prefer-dist --optimize-autoloader
            chmod -R 775 storage
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan up
          ENDSSH