name: Deploy Olshop API
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PEM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOSTNAME }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
          AWS_HOSTNAME: ${{ secrets.AWS_HOSTNAME }}
          AWS_PORT: 22
          AWS_PATH_PROJECT: ${{ secrets.AWS_PATH_PROJECT }}
        run: |
          echo "Deployment started ..."
          cd ${{ secrets.AWS_PATH_PROJECT }}
          git checkout .
          git clean -f -d
          git fetch --all
          git reset --hard origin/main
          git pull origin main
          sudo chmod -R 777 bootstrap/cache
          sudo chmod -R 777 storage
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          php artisan config:cache
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          php artisan migrate --force
          git add .
          git commit -am "Update from automation deploy"
          git push origin main
          echo "Deployment finished!"
        
